name: twod-mcda

channels:
  - conda-forge

dependencies:
  - python=3.13
  - numpy
  - scipy
  - numba
  - matplotlib
  - seaborn
  - holoviews
  - hvplot
  - panel
  - bokeh
  - cartopy
  - jupyterlab
  - jupyter_bokeh
  - ipykernel
  - pyhdf
  - netcdf4
  - pyyaml
  - pip
  - pip:
      - cmlidar
