[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "twod_mcda"
dynamic = ["version"]
description = "2D McDA processing pipeline for CALIOP L1 data"


[tool.setuptools]
package-dir = {"" = "src"}


[tool.setuptools.packages.find]
where = ["src"]


[tool.setuptools.package-data]
twod_mcda = ["lidar_data_altitudes.pkl"]


[tool.setuptools.dynamic]
version = {attr = "twod_mcda.__version__"}
