"""Constants defined by CALIPSO/CALIOP products."""

import pickle
import re
from pathlib import Path

WAVELENGTH_532 = 532
WAVELENGTH_1064 = 1064
CALIOP_L1_PRODUCT_TYPE = "Standard"

FILL_VALUE_FLOAT = -9999.0
FILL_VALUE_SHORT = -127
FILL_VALUE_FLOAT_EXTINCTION = -333.0
FILL_VALUE_EXTINCTION_QC = 32768
FILL_VALUE_ODCOD_QC = 4294967295
FILL_VALUE_OPACITY_FLAG = 99

IGBP_FLAG_OPEN_SHRUBLAND = 7
IGBP_FLAG_BARREN_DESERT = 16
IGBP_FLAG_WATER = 17

NUMBER_OF_VERTICAL_BINS = 583
NUMBER_OF_VERTICAL_BINS_MET = 33

#: Names of the two native vertical dimensions, as labelled by the reading stack
LIDAR_ALTITUDE_DIMENSION = "lidar_altitude"
MET_ALTITUDE_DIMENSION = "met_altitude"
NUMBER_OF_VERTICAL_BINS_05KMPRO = 399

REGION_5_ALTITUDE_BOUNDARIES = (40.0, 30.1)
REGION_4_ALTITUDE_BOUNDARIES = (30.1, 20.2)
REGION_3_ALTITUDE_BOUNDARIES = (20.2, 8.2)
REGION_2_ALTITUDE_BOUNDARIES = (8.2, -0.5)
REGION_1_ALTITUDE_BOUNDARIES = (-0.5, -2.0)

LAYER_ALTITUDE_R5_INDEX_RANGE = (0, 32)
LAYER_ALTITUDE_R4_INDEX_RANGE = (33, 87)
LAYER_ALTITUDE_R3_INDEX_RANGE = (88, 287)
LAYER_ALTITUDE_R2_INDEX_RANGE = (288, 577)
LAYER_ALTITUDE_R1_INDEX_RANGE = (578, 582)

N_BINS_R5 = LAYER_ALTITUDE_R5_INDEX_RANGE[1] - LAYER_ALTITUDE_R5_INDEX_RANGE[0] + 1
N_BINS_R4 = LAYER_ALTITUDE_R4_INDEX_RANGE[1] - LAYER_ALTITUDE_R4_INDEX_RANGE[0] + 1
N_BINS_R3 = LAYER_ALTITUDE_R3_INDEX_RANGE[1] - LAYER_ALTITUDE_R3_INDEX_RANGE[0] + 1
N_BINS_R2 = LAYER_ALTITUDE_R2_INDEX_RANGE[1] - LAYER_ALTITUDE_R2_INDEX_RANGE[0] + 1
N_BINS_R1 = LAYER_ALTITUDE_R1_INDEX_RANGE[1] - LAYER_ALTITUDE_R1_INDEX_RANGE[0] + 1

N_15M_BINS_PER_BIN_R5 = 20
N_15M_BINS_PER_BIN_R4 = 12
N_15M_BINS_PER_BIN_R3 = 4
N_15M_BINS_PER_BIN_R2 = 2
N_15M_BINS_PER_BIN_R1 = 20

N_30M_BINS_PER_BIN_R5 = int(N_15M_BINS_PER_BIN_R5 / 2)
N_30M_BINS_PER_BIN_R4 = int(N_15M_BINS_PER_BIN_R4 / 2)
N_30M_BINS_PER_BIN_R3 = int(N_15M_BINS_PER_BIN_R3 / 2)
N_30M_BINS_PER_BIN_R2 = int(N_15M_BINS_PER_BIN_R2 / 2)
N_30M_BINS_PER_BIN_R1 = int(N_15M_BINS_PER_BIN_R1 / 2)

SIZE_30M_BIN_KM = 0.03

N_LASER_PULSES_PER_333m = 1
N_LASER_PULSES_PER_1km = 3
N_LASER_PULSES_PER_1667m = 5
N_LASER_PULSES_PER_5km = 15

N_333M_BINS_PER_BIN_R5 = 15
N_333M_BINS_PER_BIN_R4 = 5
N_333M_BINS_PER_BIN_R3 = 3
N_333M_BINS_PER_BIN_R2 = 1
N_333M_BINS_PER_BIN_R1 = 1

LIDAR_ALTITUDES_FILE = (
    Path(__file__).resolve().parent / "resources" / "lidar_data_altitudes.pkl"
)

with LIDAR_ALTITUDES_FILE.open("rb") as file:
    LIDAR_DATA_ALTITUDES = pickle.load(file)["Lidar_Data_Altitudes"]

GRANULE_TIME_FMT = "%Y-%m-%dT%H-%M-%S"

CAL_LID_FILENAME_FMT = (
    "CAL_LID_%s-%s-%s.%s.hdf"  # product (ex: 'L2_VFM'), type (ex: Standard),
)
# version (ex: 'V4-10'),
# granule (ex: '2010-06-01T01-33-28ZN')

CAL_IIR_FILENAME_FMT = (
    "CAL_IIR_%s-%s-%s.%s.hdf"  # product (ex: 'L2_Track'), type (ex: Standard),
)
# version (ex: 'V4-10'),
# granule (ex: '2010-06-01T01-33-28ZN')

CAL_LID_L1_FILENAME_PATTERN = re.compile(
    r"CAL_LID_L1-[^-]+-V(?:\d+)-(?:\d+)\."
    r"(\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2})(Z[DN])\.hdf"
)
