"""CALIOP Level 1 variable registry used by the processing workflow."""

# Variables read by the current 2D-McDA algorithm, in its historical order.
CALIOP_L1_PROCESSING_VARIABLES = (
    "Latitude",
    "Longitude",
    "Lidar_Data_Altitudes",
    "Profile_ID",
    "Profile_Time",
    "Profile_UTC_Time",
    "Perpendicular_Attenuated_Backscatter_532",
    "Parallel_Attenuated_Backscatter_532",
    "Attenuated_Backscatter_1064",
    "Parallel_RMS_Baseline_532",
    "Perpendicular_RMS_Baseline_532",
    "RMS_Baseline_1064",
    "Spacecraft_Altitude",
    "Calibration_Constant_532",
    "Calibration_Constant_1064",
    "Depolarization_Gain_Ratio_532",
    "Laser_Energy_532",
    "Laser_Energy_1064",
    "Parallel_Amplifier_Gain_532",
    "Perpendicular_Amplifier_Gain_532",
    "Amplifier_Gain_1064",
    "Molecular_Parallel_Attenuated_Backscatter_532",
    "Molecular_Perpendicular_Attenuated_Backscatter_532",
    "Molecular_Attenuated_Backscatter_1064",
    "Molecular_Parallel_Backscatter_532",
    "Molecular_Perpendicular_Backscatter_532",
    "Molecular_Backscatter_1064",
    "Attenuated_Scattering_Ratio_Uncertainty_Standard_Deviation_532_Parallel",
    "Attenuated_Scattering_Ratio_Uncertainty_Standard_Deviation_532_Perpendicular",
    "Attenuated_Scattering_Ratio_Uncertainty_Standard_Deviation_1064",
    "Temperature",
    "IGBP_Surface_Type",
    "Surface_Elevation",
    "Off_Nadir_Angle",
)
